services:
  lux_grid_watcher:
    image: ghcr.io/hoang-rio/lux-grid-watcher:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: lux_grid_watcher
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    volumes:
      - ../.env:/app/.env:ro
      - ../db:/app/db:rw
    ports:
      - 8088:8088