FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Source code is mounted in docker-compose.dev.yml
CMD ["python", "app.py"]
