services:
  postgres:
    image: postgres:17-alpine
    container_name: lux_pg_prod
    restart: unless-stopped
    env_file:
      - ./env/prod.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  lux_web_viewer:
    image: ghcr.io/hoang-rio/lux-web-viewer:SaaS
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: lux_web_viewer_prod
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./env/prod.env
    environment:
      POSTGRES_DB_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AUTH_ENABLED: "false"
    command: >
      sh -c "alembic upgrade head && python app.py"
    ports:
      - "8088:88"
      - "8443:8443"
      - "4346:4346"
    volumes:
      - fcm_admin_key.json:/app/fcm_admin_key.json:ro
volumes:
  pg_data_prod:
