services:
  lux_grid_watcher:
    image: ghcr.io/hoang-rio/lux-grid-watcher:v1.1.7
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: lux_grid_watcher
    restart: unless-stopped
    volumes:
      - ../.env:/app/.env:ro
      - ../db:/app/db:rw
    ports:
      - 88:88